node-private-key-file = "/opt/node3/nodekey"
genesis-file="/opt/node3/genesis.json"


# RPC
rpc-http-enabled=true
rpc-http-api=["ETH","NET","IBFT","EEA","PRIV"]
rpc-http-host="0.0.0.0"
rpc-http-port=10545
rpc-ws-port=10546
#graphql-http-enabled=true
#rpc-ws-enabled=true
#graphql-http-port=10547

host-allowlist=["*"]
rpc-http-cors-origins=["all"]

# Gas free
min-gas-price=0

# p2p
p2p-host="0.0.0.0"
p2p-port="30305"

# Metrics
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=10548
