# RPC
rpc-http-enabled=true
rpc-http-api=["ETH","NET","IBFT"]
rpc-http-port=4545
rpc-http-host="0.0.0.0"
rpc-ws-port=4546
#graphql-http-enabled=true
#rpc-ws-enabled=true
#graphql-http-port=4547

# Gas free
min-gas-price=0

# Metrics
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=4548


