node-private-key-file = "/opt/node2/nodekey"
genesis-file="/opt/node2/genesis.json"


# RPC
rpc-http-enabled=true
rpc-http-api=["ETH","NET","IBFT","EEA","PRIV"]
rpc-http-host="0.0.0.0"
rpc-http-port=9545
rpc-ws-port=9546
#graphql-http-enabled=true
#rpc-ws-enabled=true
#graphql-http-port=9547

host-allowlist=["*"]
rpc-http-cors-origins=["all"]

# Gas free
min-gas-price=0

# p2p
p2p-host="0.0.0.0"
p2p-port="30304"

# Metrics
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=9548
