# RPC
rpc-http-enabled=true
rpc-http-api=["ETH","NET","IBFT","EEA","PRIV"]
rpc-http-host="0.0.0.0"
rpc-ws-port=11546
#graphql-http-enabled=true
#rpc-ws-enabled=true
#graphql-http-port=11547

# Gas free
min-gas-price=0

# Metrics
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=11548



