# RPC
rpc-http-enabled=true
rpc-http-api=["ETH","NET","IBFT"]
rpc-http-port=7545
rpc-http-host="0.0.0.0"
rpc-ws-port=7546
#graphql-http-enabled=true
#rpc-ws-enabled=true
#graphql-http-port=7547

# Gas free
min-gas-price=0

# Metrics
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=7548

# Bootnodes
#bootnodes=["enode://a0c528675c564479dc5ae493a6c5cf348788e24e5f7b9807a6c0e0c5d734bb19523c86c073d4ab17fcb0a4e6e0d7e236f25f138ce90470e9cfcf1a91af0d0615@127.0.0.1:30303"]



