# RPC
rpc-http-enabled=true
rpc-http-api=["ETH","NET","IBFT","EEA","PRIV"]
rpc-http-port=8545
rpc-http-host="0.0.0.0"
rpc-ws-port=8546
#graphql-http-enabled=true
#rpc-ws-enabled=true
#graphql-http-port=8547

# Gas free
min-gas-price=0

# Metrics
#metrics-enabled=true
#metrics-host="0.0.0.0"
#metrics-port=8548

# Bootnodes
bootnodes=["enode://be767d9fad77d1c6c57f6df233d32fa18890bc358b0b24a73ac3a5923e52b3f89ad11d9de692a7142bd0b2acc33628f5ca9f40916f24d37c4c5e61fe45f54411@127.0.0.1:30303"]


