---
- name: initializing constellation
  debug:
    msg: initializing constellation

- name: get public ip
  shell: dig +short myip.opendns.com @resolver1.opendns.com 2>/dev/null || curl -s --retry 2 icanhazip.com
  register: node_ip

- name: create orion directories
  file:
    path: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - { dest: "/node2/orion", mode: "0440" }
    - { dest: "/node2/orion/keystore", mode: "0440" }

- name: copy password to file
  copy:
    dest: /node2/tmp/.account_pass
    content: |
      {{password}}

#- name: Copy constellation nodes file
#  copy:
#      src: "{{ role_path }}/files/constellation-nodes.json"
#      dest: /node2/tmp/constellation-nodes.json
#      mode: 0755

#- name: update constellation node files
#  replace:
#      path: /node2/tmp/constellation-nodes.json
#      regexp: '9000/"$'
#      replace: '9000/",'

#- name: update constellation nodes file
#  lineinfile:
#      path: /node2/tmp/constellation-nodes.json
#      regexp: "$]$"
#      insertbefore: "^]$"
#      line: '    "https://{{node_ip.stdout}}:9000/"'

#- name: Fetch constellation_nodes updated
#  fetch:
#      src: /node2/tmp/constellation-nodes.json
#      dest: "{{ role_path }}/files/"
#      flat: yes

- name: generate configuration orion file
  template:
    src: "orion.j2"
    dest: "/node2/orion/orion.conf"
    force: yes

- name: generate pair keys
  shell: cat /node2/tmp/.account_pass | orion --generatekeys nodeKey
  args:
    chdir: /node2/orion/keystore

- name: Generate shell script to execute orion service
  template:
    src: "startorion.j2"
    dest: "/node2/start-orion.sh"
    mode: 0775
    force: yes

- name: Copy service file to systemd
  copy:
    src: "{{ role_path }}/files/orion.service"
    dest: /lib/systemd/system/orion.service
    mode: 0775

- name: Enable service orion
  service:
    name: orion
    enabled: yes
